name: Deploy to VPS

on:
  push:
    branches:
      - production
  workflow_dispatch: # Позволяет запускать работу вручную

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AM_PROJECTS_SSH_PRIVATE_KEY }}
        remote-user: root
        server-ip: am-projects.ru
        port: 22

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@am-projects.ru << 'EOF'
          cd /var/www/drivers.am-projects.ru
          git pull origin production
          make install
          export NODE_OPTIONS=--max-old-space-size=8192
          rm -r -f .next
          make build
          make start
        EOF
